# Generated by Django 3.0.6 on 2020-05-29 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.FileField(null=True, upload_to='', verbose_name='头像'),
        ),
    ]
