# Generated by Django 3.0.6 on 2020-05-29 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0002_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='头像'),
        ),
    ]
