# Generated by Django 2.2.26 on 2022-02-07 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miniprogram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wechataccount',
            name='user',
            field=models.OneToOneField(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='帐号'),
        ),
    ]
