# Generated by Django 3.0.5 on 2020-04-27 03:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.0'), max_digits=8, verbose_name='支出总计')),
                ('has_invoice', models.BooleanField(default=False, verbose_name='是否有发票')),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.0'), max_digits=8, verbose_name='货物数量')),
            ],
        ),
    ]
