# Generated by Django 2.2.17 on 2020-11-10 04:03

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications', '0008_index_together_recipient_unread'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyNotification',
            fields=[
            ],
            options={
                'managed': False,
                'proxy': True,
            },
            bases=('notifications.notification',),
        ),
    ]
