# Generated by Django 2.2.14 on 2020-07-29 01:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=80, verbose_name='名称')),
                ('code', models.CharField(blank=True, max_length=32, null=True, verbose_name='编号')),
            ],
            options={
                'verbose_name': '状态',
                'verbose_name_plural': '状态',
            },
        ),
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='关联的对象ID')),
                ('status', models.CharField(choices=[('pending', '准备中'), ('cancelled', '已取消'), ('done', '已完成'), ('jumped', '已跳转')], default='pending', max_length=16, verbose_name='状态')),
                ('iteration', models.IntegerField(default=0, verbose_name='优先级')),
                ('content_type', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.ContentType', verbose_name='Content Type')),
                ('destination_state', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='transition_as_destination', to='rworkflow.State', verbose_name='目的状态')),
            ],
            options={
                'verbose_name': '流转记录',
                'verbose_name_plural': '流转记录',
            },
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='对象ID')),
                ('app_label', models.CharField(blank=True, max_length=128, null=True, verbose_name='应用名称')),
                ('model_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='模型名称')),
                ('status_field', models.CharField(blank=True, max_length=40, null=True, verbose_name='状态字段')),
                ('status_value', models.CharField(blank=True, max_length=40, null=True, verbose_name='状态值')),
                ('is_inuse', models.BooleanField(default=True, verbose_name='在用？')),
                ('weight', models.IntegerField(blank=True, default=99, null=True, verbose_name='排序权重')),
                ('content_type', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.ContentType', verbose_name='Content Type')),
                ('initial_state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workflow_this_set_as_initial_state', to='rworkflow.State', verbose_name='初始状态')),
            ],
            options={
                'verbose_name': '工作流',
                'verbose_name_plural': '工作流',
            },
        ),
        migrations.CreateModel(
            name='TransitionMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('destination_state', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='transition_meta_as_destination', to='rworkflow.State', verbose_name='目的状态')),
                ('source_state', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='transition_meta_as_source', to='rworkflow.State', verbose_name='初始状态')),
                ('workflow', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='transition_metas', to='rworkflow.Workflow', verbose_name='工作流')),
            ],
            options={
                'verbose_name': '流转元数据',
                'verbose_name_plural': '流转元数据',
                'unique_together': {('workflow', 'source_state', 'destination_state')},
            },
        ),
        migrations.CreateModel(
            name='TransitionApprovalMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('priority', models.IntegerField(blank=True, default=0, null=True, verbose_name='优先级')),
                ('groups', models.ManyToManyField(blank=True, to='auth.Group', verbose_name='权限组')),
                ('parents', models.ManyToManyField(blank=True, db_index=True, related_name='children', to='rworkflow.TransitionApprovalMeta', verbose_name='父级')),
                ('permissions', models.ManyToManyField(blank=True, to='auth.Permission', verbose_name='权限')),
                ('transition_meta', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='transition_approval_meta', to='rworkflow.TransitionMeta', verbose_name='流转元数据')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transition_approval_metas', to='rworkflow.Workflow', verbose_name='工作流')),
            ],
            options={
                'verbose_name': '流转批准元数据',
                'verbose_name_plural': '流转批准元数据',
                'unique_together': {('workflow', 'transition_meta', 'priority')},
            },
        ),
        migrations.CreateModel(
            name='TransitionApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='对象ID')),
                ('transaction_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', '准备中'), ('cancelled', '已取消'), ('done', '已完成'), ('jumped', '已跳转')], default='pending', max_length=16, verbose_name='状态')),
                ('priority', models.IntegerField(default=0, verbose_name='优先级')),
                ('content_type', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.ContentType', verbose_name='Content Type')),
                ('groups', models.ManyToManyField(to='auth.Group', verbose_name='权限组')),
                ('meta', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transition_approvals', to='rworkflow.TransitionApprovalMeta', verbose_name='元数据')),
                ('permissions', models.ManyToManyField(to='auth.Permission', verbose_name='权限')),
                ('previous', mptt.fields.TreeOneToOneField(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_transition', to='rworkflow.TransitionApproval', verbose_name='前一个流转')),
                ('transactioner', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='流转者')),
                ('transition', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='transition_approvals', to='rworkflow.Transition', verbose_name='流转')),
                ('workflow', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='transition_approvals', to='rworkflow.Workflow', verbose_name='工作流')),
            ],
            options={
                'verbose_name': '流转批准',
                'verbose_name_plural': '流转批准',
            },
        ),
        migrations.AddField(
            model_name='transition',
            name='meta',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='transitions', to='rworkflow.TransitionMeta', verbose_name='元数据'),
        ),
        migrations.AddField(
            model_name='transition',
            name='source_state',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='transition_as_source', to='rworkflow.State', verbose_name='初始状态'),
        ),
        migrations.AddField(
            model_name='transition',
            name='workflow',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='transitions', to='rworkflow.Workflow', verbose_name='工作流'),
        ),
        migrations.AddField(
            model_name='state',
            name='workflow',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='states', to='rworkflow.Workflow', verbose_name='工作流'),
        ),
    ]
