# Generated by Django 2.2.15 on 2020-08-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('rworkflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transitionapprovalmeta',
            name='orgunits',
            field=models.ManyToManyField(blank=True, db_constraint=False, to='organization.OrgUnit', verbose_name='指定部门单元'),
        ),
    ]
