# Generated by Django 2.2.14 on 2020-07-29 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rworkflow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wforder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('code', models.CharField(blank=True, max_length=32, null=True, verbose_name='编号')),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('status', models.CharField(blank=True, max_length=8, null=True, verbose_name='状态')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='transitionmeta',
            name='destination_status_value',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='目的状态值'),
        ),
        migrations.AddField(
            model_name='transitionmeta',
            name='source_status_value',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='初始状态值'),
        ),
        migrations.AddField(
            model_name='transitionmeta',
            name='status_field',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='状态字段'),
        ),
        migrations.AlterField(
            model_name='transition',
            name='iteration',
            field=models.IntegerField(default=0, verbose_name='iteration'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='initial_state',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='workflow_this_set_as_initial_state', to='rworkflow.State', verbose_name='初始状态'),
        ),
        migrations.AlterUniqueTogether(
            name='transitionapprovalmeta',
            unique_together=set(),
        ),
    ]
