# Generated by Django 2.2.15 on 2020-08-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rworkflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transitionapprovalmeta',
            name='handler_type',
            field=models.CharField(choices=[('users', '指定用户'), ('positions', '指定岗位'), ('roles', '指定角色'), ('units', '指定部门'), ('subbmiter', '提交人'), ('custom_function', '自定义审批处理类'), ('custom_sql', '自定义SQL处理人')], default='subbmiter', max_length=40, verbose_name='审批处理类型'),
        ),
    ]
