# Generated by Django 2.2.14 on 2020-07-29 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rworkflow', '0002_auto_20200729_1402'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wforder',
            options={'verbose_name': '工单', 'verbose_name_plural': '工单'},
        ),
        migrations.RemoveField(
            model_name='state',
            name='workflow',
        ),
        migrations.AlterField(
            model_name='state',
            name='code',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='wforder',
            name='code',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='wforder',
            name='status',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='状态'),
        ),
    ]
