# Generated by Django 2.2.14 on 2020-07-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rworkflow', '0003_auto_20200729_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='name',
            field=models.CharField(default='', max_length=80, verbose_name='名称'),
            preserve_default=False,
        ),
    ]
