# Generated by Django 2.2.15 on 2020-08-13 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rworkflow', '0003_auto_20200812_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transitionapprovalmeta',
            name='can_edit',
        ),
        migrations.RemoveField(
            model_name='transitionapprovalmeta',
            name='can_suggestion',
        ),
        migrations.RemoveField(
            model_name='transitionapprovalmeta',
            name='is_suggestion_required',
        ),
        migrations.RemoveField(
            model_name='transitionapprovalmeta',
            name='need_take',
        ),
        migrations.AddField(
            model_name='state',
            name='can_edit',
            field=models.BooleanField(default=False, verbose_name='可编辑？'),
        ),
        migrations.AddField(
            model_name='state',
            name='can_suggestion',
            field=models.BooleanField(default=False, verbose_name='可填写处理意见？'),
        ),
        migrations.AddField(
            model_name='state',
            name='is_suggestion_required',
            field=models.BooleanField(default=False, verbose_name='处理意见是否必填？'),
        ),
        migrations.AddField(
            model_name='state',
            name='need_take',
            field=models.BooleanField(default=False, verbose_name='需要处理人接单？'),
        ),
    ]
