# Generated by Django 2.2.14 on 2020-07-29 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rworkflow', '0004_workflow_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transition',
            options={'verbose_name': '流转', 'verbose_name_plural': '流转'},
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='initial_state',
        ),
        migrations.AddField(
            model_name='state',
            name='is_start',
            field=models.BooleanField(default=False, verbose_name='起始状态？'),
        ),
        migrations.AddField(
            model_name='state',
            name='is_stop',
            field=models.BooleanField(default=False, verbose_name='结束状态？'),
        ),
        migrations.AddField(
            model_name='state',
            name='workflow',
            field=models.ForeignKey(db_constraint=False, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='states', to='rworkflow.Workflow', verbose_name='工作流'),
            preserve_default=False,
        ),
    ]
