# Generated by Django 2.2.14 on 2020-07-29 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rworkflow', '0005_auto_20200729_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transitionmeta',
            name='destination_status_value',
        ),
        migrations.RemoveField(
            model_name='transitionmeta',
            name='source_status_value',
        ),
        migrations.RemoveField(
            model_name='transitionmeta',
            name='status_field',
        ),
    ]
