# Generated by Django 2.2.14 on 2020-07-29 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rworkflow', '0006_auto_20200729_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('code', models.CharField(blank=True, max_length=80, null=True, verbose_name='编号')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='对象ID')),
                ('start_at', models.DateTimeField(auto_now_add=True, verbose_name='发起时间')),
                ('initialized', models.BooleanField(default=False, verbose_name='已初始化？')),
                ('starter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='发起人')),
                ('workflow', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='rworkflow.Workflow', verbose_name='关联的工作流模型')),
            ],
            options={
                'verbose_name': '工作流实例',
                'verbose_name_plural': '工作流实例',
                'default_permissions': ('view',),
            },
        ),
    ]
