# Generated by Django 2.2.15 on 2020-08-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rworkflow', '0006_auto_20200813_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='transitionapproval',
            name='weight',
            field=models.IntegerField(blank=True, default=9, null=True, verbose_name='排序权重'),
        ),
        migrations.AddField(
            model_name='transitionapprovalmeta',
            name='weight',
            field=models.IntegerField(blank=True, default=9, null=True, verbose_name='排序权重'),
        ),
        migrations.AlterField(
            model_name='transition',
            name='code',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='transition',
            name='iteration',
            field=models.IntegerField(default=0, verbose_name='迭代层级'),
        ),
        migrations.AlterField(
            model_name='transition',
            name='name',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='transitionapproval',
            name='code',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='transitionapproval',
            name='name',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='transitionapprovalmeta',
            name='code',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='transitionapprovalmeta',
            name='name',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='transitionapprovalmeta',
            name='priority',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='优先级'),
        ),
        migrations.AlterField(
            model_name='transitionmeta',
            name='code',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='transitionmeta',
            name='name',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='transitionmeta',
            name='weight',
            field=models.IntegerField(blank=True, default=9, null=True, verbose_name='排序权重'),
        ),
    ]
