# Generated by Django 2.2.14 on 2020-07-29 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rworkflow', '0007_workflowinstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='wforder',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='申请者'),
        ),
    ]
