# Generated by Django 2.2.15 on 2020-08-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rworkflow', '0007_auto_20200813_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowinstance',
            name='finish_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='结束时间'),
        ),
        migrations.AddField(
            model_name='workflowinstance',
            name='is_finish',
            field=models.BooleanField(default=False, editable=False, verbose_name='已结束？'),
        ),
    ]
