# Generated by Django 2.2.14 on 2020-07-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rworkflow', '0008_wforder_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='wforder',
            name='tp',
            field=models.CharField(blank=True, choices=[('00', '加班申请'), ('10', '调休申请'), ('20', '假期申请')], max_length=16, null=True, verbose_name='工单类型'),
        ),
        migrations.AlterField(
            model_name='wforder',
            name='code',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='工单编号'),
        ),
        migrations.AlterField(
            model_name='wforder',
            name='title',
            field=models.CharField(max_length=128, verbose_name='工单标题'),
        ),
    ]
