# Generated by Django 2.2.15 on 2020-08-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rworkflow', '0008_auto_20200813_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transitionapproval',
            name='status',
            field=models.CharField(choices=[('pending', '准备中'), ('approved', '已处理'), ('cancelled', '已取消'), ('jumped', '已跳转')], db_index=True, default='pending', max_length=16, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='transitionapprovalmeta',
            name='parents',
            field=models.ManyToManyField(blank=True, db_constraint=False, db_index=True, related_name='children', to='rworkflow.TransitionApprovalMeta', verbose_name='父级'),
        ),
    ]
