# Generated by Django 2.2.14 on 2020-07-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rworkflow', '0010_wforder_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='order_relation_config',
            field=models.CharField(blank=True, choices=[('00', '关联到工单表'), ('10', '由工单选择')], max_length=16, null=True, verbose_name='工作流与工单的关系配置'),
        ),
    ]
