# Generated by Django 2.2.15 on 2020-08-13 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rworkflow', '0010_auto_20200813_1708'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transitionmeta',
            unique_together={('workflow', 'source_state', 'destination_state')},
        ),
    ]
