# Generated by Django 2.2.14 on 2020-07-29 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rworkflow', '0011_workflow_order_relation_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='order_relation_config',
            field=models.CharField(choices=[('00', '通过Content Type配置给所有工单'), ('10', '通过工单关联工作流外键主动选择')], default='00', max_length=16, verbose_name='工作流与工单的关系配置'),
        ),
    ]
