# Generated by Django 2.2.14 on 2020-07-29 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rworkflow', '0012_auto_20200729_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='wforder',
            name='workflow',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'order_relation_config': '10'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='rworkflow.Workflow', verbose_name='工作流程'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='order_relation_config',
            field=models.CharField(choices=[('00', '通过Content Type配置给所有工单'), ('10', '通过工单外键主动选择工作流')], default='00', max_length=16, verbose_name='工作流与工单的关系配置'),
        ),
    ]
