# Generated by Django 2.2.15 on 2020-08-14 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rworkflow', '0012_auto_20200813_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transitionapproval',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='transitionapproval',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='transition',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='transition',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
    ]
