# Generated by Django 2.2.15 on 2020-08-14 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rworkflow', '0013_auto_20200814_0928'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='名称')),
                ('memo', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('value_tp', models.CharField(choices=[('bool', '布尔值'), ('char', '字符串'), ('text', '文本值'), ('int', '整型值'), ('bigint', '大整型值'), ('posint', '正整型值'), ('float', '浮点值'), ('binary', '二进制值'), ('decimal', '定点值'), ('time', '时间值'), ('date', '日期值'), ('datetime', '日期时间值'), ('duration', '时间间隔值'), ('file', '文件'), ('image', '图片'), ('choice', '单选值'), ('multiple_choice', '多选值')], default='bool', max_length=40, verbose_name='值类型')),
                ('bool_value', models.BooleanField(blank=True, null=True, verbose_name='布尔值')),
                ('char_value', models.CharField(blank=True, max_length=255, null=True, verbose_name='字符串值')),
                ('text_value', models.TextField(blank=True, null=True, verbose_name='文本值')),
                ('int_value', models.IntegerField(blank=True, null=True, verbose_name='整型值')),
                ('bigint_value', models.BigIntegerField(blank=True, null=True, verbose_name='大整型值')),
                ('posint_value', models.PositiveIntegerField(blank=True, null=True, verbose_name='正整型值')),
                ('float_value', models.FloatField(blank=True, null=True, verbose_name='浮点值')),
                ('binary_value', models.BinaryField(blank=True, null=True, verbose_name='二进制值')),
                ('decimal_value', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True, verbose_name='定点值')),
                ('time_value', models.TimeField(blank=True, null=True, verbose_name='时间值')),
                ('date_value', models.DateField(blank=True, null=True, verbose_name='日期值')),
                ('datetime_value', models.DateTimeField(blank=True, null=True, verbose_name='日期时间值')),
                ('duration_value', models.DurationField(blank=True, null=True, verbose_name='时间间隔值')),
                ('file_value', models.FileField(blank=True, null=True, upload_to='', verbose_name='文件')),
                ('image_value', models.ImageField(blank=True, null=True, upload_to='', verbose_name='图片')),
                ('choice_value', models.CharField(blank=True, max_length=255, null=True, verbose_name='单选值')),
                ('multiple_choice_value', models.TextField(blank=True, null=True, verbose_name='多选值')),
                ('is_choice_combo', models.BooleanField(default=False, verbose_name='choice控件是否以combo方式选择')),
                ('is_choice_async', models.BooleanField(default=False, verbose_name='choice控件是否异步加载')),
            ],
            options={
                'verbose_name': '额外参数',
                'verbose_name_plural': '额外参数',
            },
        ),
        migrations.CreateModel(
            name='ExtraParamMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('created_by', models.CharField(blank=True, db_index=True, default='', max_length=80, verbose_name='创建者')),
                ('updated_by', models.CharField(blank=True, default='', max_length=80, verbose_name='修改者')),
                ('name', models.CharField(max_length=80, verbose_name='名称')),
                ('code', models.CharField(blank=True, default='', max_length=40, verbose_name='编号')),
                ('is_active', models.BooleanField(default=True, verbose_name='在用？')),
                ('memo', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('value_tp', models.CharField(choices=[('bool', '布尔值'), ('char', '字符串'), ('text', '文本值'), ('int', '整型值'), ('bigint', '大整型值'), ('posint', '正整型值'), ('float', '浮点值'), ('binary', '二进制值'), ('decimal', '定点值'), ('time', '时间值'), ('date', '日期值'), ('datetime', '日期时间值'), ('duration', '时间间隔值'), ('file', '文件'), ('image', '图片'), ('choice', '单选值'), ('multiple_choice', '多选值')], default='bool', max_length=40, verbose_name='值类型')),
                ('is_choice_combo', models.BooleanField(default=False, verbose_name='choice控件是否以combo方式选择')),
                ('is_choice_async', models.BooleanField(default=False, verbose_name='choice控件是否异步加载')),
            ],
            options={
                'verbose_name': '额外参数元数据',
                'verbose_name_plural': '额外参数元数据',
            },
        ),
        migrations.CreateModel(
            name='ExtraParamChoiceMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('created_by', models.CharField(blank=True, db_index=True, default='', max_length=80, verbose_name='创建者')),
                ('updated_by', models.CharField(blank=True, default='', max_length=80, verbose_name='修改者')),
                ('name', models.CharField(max_length=80, verbose_name='名称')),
                ('display_value', models.CharField(blank=True, default='', max_length=255, verbose_name='数值')),
                ('extra_param_meta', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra_param_metas', to='rworkflow.ExtraParamMeta', verbose_name='额外参数元数据')),
            ],
            options={
                'verbose_name': '参数选择值元数据',
                'verbose_name_plural': '参数选择值元数据',
            },
        ),
        migrations.CreateModel(
            name='ExtraParamChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('created_by', models.CharField(blank=True, db_index=True, default='', max_length=80, verbose_name='创建者')),
                ('updated_by', models.CharField(blank=True, default='', max_length=80, verbose_name='修改者')),
                ('name', models.CharField(max_length=80, verbose_name='名称')),
                ('display_value', models.CharField(blank=True, default='', max_length=255, verbose_name='数值')),
                ('extra_param', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra_param_choices', to='rworkflow.ExtraParam', verbose_name='额外参数')),
                ('meta', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extra_param_choices', to='rworkflow.ExtraParamChoiceMeta', verbose_name='元数据')),
            ],
            options={
                'verbose_name': '参数选择值',
                'verbose_name_plural': '参数选择值',
            },
        ),
        migrations.AddField(
            model_name='extraparam',
            name='meta',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extra_params', to='rworkflow.ExtraParamMeta', verbose_name='元数据'),
        ),
    ]
