# Generated by Django 2.2.15 on 2020-08-14 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rworkflow', '0014_auto_20200814_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraparam',
            name='wo',
            field=models.ForeignKey(db_constraint=False, default=0, on_delete=django.db.models.deletion.CASCADE, related_name='extra_params', to='rworkflow.Wforder', verbose_name='工单'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extraparammeta',
            name='workflow',
            field=models.ForeignKey(db_constraint=False, default=0, on_delete=django.db.models.deletion.CASCADE, related_name='extra_param_metas', to='rworkflow.Workflow', verbose_name='工作流程'),
            preserve_default=False,
        ),
    ]
