# Generated by Django 2.2.14 on 2020-07-29 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rworkflow', '0014_auto_20200729_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transitionapproval',
            name='level',
        ),
        migrations.RemoveField(
            model_name='transitionapproval',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='transitionapproval',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='transitionapproval',
            name='tree_id',
        ),
    ]
