# Generated by Django 2.2.14 on 2020-07-30 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rworkflow', '0015_auto_20200729_1654'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transitionmeta',
            options={'ordering': ('workflow', 'weight'), 'verbose_name': '流转元数据', 'verbose_name_plural': '流转元数据'},
        ),
        migrations.AddField(
            model_name='transitionmeta',
            name='weight',
            field=models.IntegerField(blank=True, default=99, null=True, verbose_name='排序权重'),
        ),
        migrations.AlterField(
            model_name='transitionapproval',
            name='previous',
            field=models.OneToOneField(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_transition', to='rworkflow.TransitionApproval', verbose_name='前一个流转'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='status_field',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='状态字段'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='status_value',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='状态值'),
        ),
    ]
