# Generated by Django 2.2.15 on 2020-08-14 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rworkflow', '0015_auto_20200814_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraparam',
            name='weight',
            field=models.IntegerField(blank=True, default=9, null=True, verbose_name='排序权重'),
        ),
        migrations.AddField(
            model_name='extraparamchoice',
            name='weight',
            field=models.IntegerField(blank=True, default=9, null=True, verbose_name='排序权重'),
        ),
        migrations.AddField(
            model_name='extraparamchoicemeta',
            name='weight',
            field=models.IntegerField(blank=True, default=9, null=True, verbose_name='排序权重'),
        ),
        migrations.AddField(
            model_name='extraparammeta',
            name='weight',
            field=models.IntegerField(blank=True, default=9, null=True, verbose_name='排序权重'),
        ),
    ]
