# Generated by Django 2.2.15 on 2020-08-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rworkflow', '0016_auto_20200814_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transitionapprovalmeta',
            name='handler_type',
            field=models.CharField(choices=[('users', '指定用户'), ('positions', '指定岗位'), ('roles', '指定角色'), ('units', '指定部门'), ('subbmiter', '提交人'), ('custom_function', '自定义审批处理类'), ('custom_sql', '自定义SQL处理人')], default='subbmiter', max_length=40, verbose_name='处理人类型'),
        ),
        migrations.AlterField(
            model_name='transitionapprovalmeta',
            name='user_handler_function',
            field=models.CharField(blank=True, choices=[('ParentPosition', '提交人的上级')], max_length=80, null=True, verbose_name='处理人处理函数'),
        ),
    ]
