# Generated by Django 2.2.14 on 2020-07-30 02:34

from django.db import migrations
import django.db.models.deletion
import rworkflow.models.fields.state


class Migration(migrations.Migration):

    dependencies = [
        ('rworkflow', '0016_auto_20200730_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='wforder',
            name='rstatus',
            field=rworkflow.models.fields.state.StateField(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rworkflow.State', verbose_name='状态'),
        ),
    ]
