# Generated by Django 2.2.15 on 2020-08-14 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('rworkflow', '0017_auto_20200814_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraparam',
            name='content_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.ContentType', verbose_name='Content Type'),
        ),
        migrations.AddField(
            model_name='extraparam',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='对象ID'),
        ),
    ]
