# Generated by Django 2.2.14 on 2020-07-30 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rworkflow', '0017_wforder_rstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='is_inuse',
            field=models.BooleanField(default=True, verbose_name='在用？'),
        ),
        migrations.AddField(
            model_name='state',
            name='weight',
            field=models.IntegerField(blank=True, default=99, null=True, verbose_name='排序权重'),
        ),
    ]
