# Generated by Django 2.2.15 on 2020-08-14 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rworkflow', '0018_auto_20200814_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraparam',
            name='required',
            field=models.BooleanField(default=False, verbose_name='必填？'),
        ),
        migrations.AddField(
            model_name='extraparammeta',
            name='required',
            field=models.BooleanField(default=False, verbose_name='必填？'),
        ),
    ]
