# Generated by Django 2.2.14 on 2020-07-30 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rworkflow', '0018_auto_20200730_1100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ('workflow', 'weight', 'code'), 'verbose_name': '状态', 'verbose_name_plural': '状态'},
        ),
    ]
