# Generated by Django 2.2.15 on 2020-08-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rworkflow', '0019_auto_20200814_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraparam',
            name='decimal_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='定点值'),
        ),
    ]
