# Generated by Django 2.2.14 on 2020-07-30 05:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rworkflow', '0019_auto_20200730_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='transitionapprovalmeta',
            name='email_notice',
            field=models.BooleanField(default=True, verbose_name='邮件通知'),
        ),
        migrations.AddField(
            model_name='transitionapprovalmeta',
            name='handler',
            field=models.TextField(blank=True, null=True, verbose_name='处理人SQL'),
        ),
        migrations.AddField(
            model_name='transitionapprovalmeta',
            name='handler_type',
            field=models.CharField(choices=[('00', '指定用户'), ('90', '提交人')], default='00', max_length=16, verbose_name='处理类型'),
        ),
        migrations.AddField(
            model_name='transitionapprovalmeta',
            name='next_user_handler',
            field=models.CharField(blank=True, choices=[('ParentPosition', '提交人的上级')], max_length=80, null=True, verbose_name='next用户处理类'),
        ),
        migrations.AddField(
            model_name='transitionapprovalmeta',
            name='short_message_notice',
            field=models.BooleanField(default=False, verbose_name='短信通知'),
        ),
        migrations.AddField(
            model_name='transitionapprovalmeta',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='指定用户'),
        ),
        migrations.AddField(
            model_name='transitionapprovalmeta',
            name='weixin_notice',
            field=models.BooleanField(default=False, verbose_name='微信通知'),
        ),
        migrations.AlterField(
            model_name='transitionapprovalmeta',
            name='priority',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='排序'),
        ),
    ]
