# Generated by Django 2.2.15 on 2020-08-11 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rworkflow', '0020_auto_20200730_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state',
            old_name='is_inuse',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='workflow',
            old_name='is_inuse',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='status_value',
        ),
        migrations.AddField(
            model_name='transition',
            name='destination_state_value',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='目的状态值'),
        ),
        migrations.AddField(
            model_name='transition',
            name='source_state_value',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='初始状态值'),
        ),
        migrations.AddField(
            model_name='transitionmeta',
            name='destination_state_value',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='目的状态值'),
        ),
        migrations.AddField(
            model_name='transitionmeta',
            name='source_state_value',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='初始状态值'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='init_status_value',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='初始状态值'),
        ),
    ]
