# Generated by Django 2.2.15 on 2020-08-17 06:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rworkflow', '0020_auto_20200814_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraparam',
            name='code',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='transitionapproval',
            name='users',
            field=models.ManyToManyField(blank=True, db_constraint=False, related_name='transition_approvals', to=settings.AUTH_USER_MODEL, verbose_name='处理人'),
        ),
    ]
