# Generated by Django 2.2.15 on 2020-08-11 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rworkflow', '0021_auto_20200811_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=80, verbose_name='名称')),
                ('short', models.CharField(blank=True, max_length=80, null=True, verbose_name='简称')),
                ('code', models.CharField(blank=True, max_length=80, null=True, verbose_name='编号')),
                ('pinyin', models.CharField(blank=True, max_length=80, null=True, verbose_name='拼音/英文')),
                ('spec', models.CharField(blank=True, default='', max_length=255, verbose_name='简单描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='在用？')),
                ('weight', models.IntegerField(default=99, verbose_name='排序权重')),
            ],
            options={
                'verbose_name': '工作流分类',
                'verbose_name_plural': '工作流分类',
                'ordering': ('weight', 'code'),
            },
        ),
    ]
