# Generated by Django 2.2.15 on 2020-08-17 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rworkflow', '0021_auto_20200817_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraparam',
            name='workflow',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='extra_params', to='rworkflow.Workflow', verbose_name='工作流程'),
        ),
    ]
