# Generated by Django 2.2.15 on 2020-08-11 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rworkflow', '0022_workflowcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflows', to='rworkflow.WorkflowCategory', verbose_name='类别'),
        ),
    ]
