# Generated by Django 2.2.15 on 2020-08-17 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rworkflow', '0022_extraparam_workflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('created_by', models.CharField(blank=True, db_index=True, default='', max_length=80, verbose_name='创建者')),
                ('updated_by', models.CharField(blank=True, default='', max_length=80, verbose_name='修改者')),
                ('name', models.CharField(max_length=80, verbose_name='名称')),
                ('code', models.CharField(blank=True, default='', max_length=40, verbose_name='编号')),
                ('is_active', models.BooleanField(default=True, verbose_name='在用？')),
                ('weight', models.IntegerField(blank=True, default=9, null=True, verbose_name='排序权重')),
                ('rule', models.TextField(verbose_name='规则')),
                ('workflow', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='condition_metas', to='rworkflow.Workflow', verbose_name='工作流程')),
            ],
            options={
                'verbose_name': '条件元数据',
                'verbose_name_plural': '条件元数据',
            },
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='名称')),
                ('code', models.CharField(blank=True, default='', max_length=40, verbose_name='编号')),
                ('weight', models.IntegerField(blank=True, default=9, null=True, verbose_name='排序权重')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('rule', models.TextField(verbose_name='规则')),
                ('meta', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='rworkflow.ConditionMeta', verbose_name='流转条件元数据')),
                ('workflow', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='rworkflow.Workflow', verbose_name='工作流程')),
                ('workorder', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='rworkflow.Wforder', verbose_name='关联的工单')),
            ],
            options={
                'verbose_name': '流转条件',
                'verbose_name_plural': '流转条件',
            },
        ),
    ]
