# Generated by Django 2.2.15 on 2020-08-11 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rworkflow', '0023_workflow_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='wforder',
            name='workflow_category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='rworkflow.WorkflowCategory', verbose_name='流程类别'),
        ),
        migrations.AddField(
            model_name='wforder',
            name='workflow_instance',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rworkflow.WorkflowInstance', verbose_name='流程实例'),
        ),
        migrations.AlterField(
            model_name='wforder',
            name='workflow',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='rworkflow.Workflow', verbose_name='工单流程'),
        ),
    ]
