# Generated by Django 2.2.15 on 2020-08-17 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rworkflow', '0023_condition_conditionmeta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conditionmeta',
            options={'verbose_name': '流转条件元数据', 'verbose_name_plural': '流转条件元数据'},
        ),
        migrations.AddField(
            model_name='conditionmeta',
            name='transition_approvale_meta',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='condition_metas', to='rworkflow.TransitionApprovalMeta', verbose_name='流转批准元数据'),
        ),
    ]
