# Generated by Django 2.2.15 on 2020-08-11 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rworkflow', '0024_auto_20200811_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='status_field',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='状态字段'),
        ),
        migrations.AddField(
            model_name='state',
            name='status_value',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='状态值'),
        ),
    ]
