# Generated by Django 2.2.15 on 2020-08-18 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rworkflow', '0024_auto_20200817_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='transitionapproval',
            name='rule',
            field=models.TextField(blank=True, default='', verbose_name='条件判断规则'),
        ),
        migrations.AddField(
            model_name='transitionapproval',
            name='rule_result',
            field=models.BooleanField(blank=True, null=True, verbose_name='条件判断结果'),
        ),
        migrations.AddField(
            model_name='transitionapprovalmeta',
            name='rule',
            field=models.TextField(blank=True, default='', verbose_name='条件判断规则'),
        ),
    ]
