# Generated by Django 2.2.15 on 2020-08-11 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rworkflow', '0025_auto_20200811_1007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ('workflow', 'weight', 'code'), 'verbose_name': '流程状态', 'verbose_name_plural': '流程状态'},
        ),
        migrations.AlterModelOptions(
            name='transition',
            options={'verbose_name': '流程流转', 'verbose_name_plural': '流程流转'},
        ),
        migrations.AlterModelOptions(
            name='transitionapproval',
            options={'verbose_name': '流程批准', 'verbose_name_plural': '流程批准'},
        ),
        migrations.AlterModelOptions(
            name='transitionapprovalmeta',
            options={'verbose_name': '批准元数据', 'verbose_name_plural': '批准元数据'},
        ),
        migrations.AlterModelOptions(
            name='workflow',
            options={'verbose_name': '工作流程', 'verbose_name_plural': '工作流程'},
        ),
        migrations.AlterModelOptions(
            name='workflowcategory',
            options={'ordering': ('weight', 'code'), 'verbose_name': '流程分类', 'verbose_name_plural': '流程分类'},
        ),
        migrations.AlterModelOptions(
            name='workflowinstance',
            options={'default_permissions': ('view',), 'verbose_name': '流程实例', 'verbose_name_plural': '流程实例'},
        ),
        migrations.AlterField(
            model_name='state',
            name='workflow',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='states', to='rworkflow.Workflow', verbose_name='工作流程'),
        ),
        migrations.AlterField(
            model_name='transitionapprovalmeta',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transition_approval_metas', to='rworkflow.Workflow', verbose_name='工作流程'),
        ),
    ]
