# Generated by Django 2.2.15 on 2020-08-18 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rworkflow', '0025_auto_20200818_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='transitionapprovalmeta',
            name='rule_enabled',
            field=models.BooleanField(default=False, verbose_name='是否启用条件判断？'),
        ),
    ]
