# Generated by Django 2.2.15 on 2020-08-11 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rworkflow', '0027_auto_20200811_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='can_edit',
        ),
        migrations.RemoveField(
            model_name='state',
            name='can_take',
        ),
        migrations.AddField(
            model_name='transitionapproval',
            name='can_edit',
            field=models.BooleanField(default=False, verbose_name='可编辑？'),
        ),
        migrations.AddField(
            model_name='transitionapproval',
            name='can_take',
            field=models.BooleanField(default=False, verbose_name='可接单？'),
        ),
        migrations.AddField(
            model_name='transitionapproval',
            name='email_notice',
            field=models.BooleanField(default=True, verbose_name='邮件通知'),
        ),
        migrations.AddField(
            model_name='transitionapproval',
            name='short_message_notice',
            field=models.BooleanField(default=False, verbose_name='短信通知'),
        ),
        migrations.AddField(
            model_name='transitionapproval',
            name='users',
            field=models.ManyToManyField(blank=True, db_constraint=False, related_name='_transitionapproval_users_+', to=settings.AUTH_USER_MODEL, verbose_name='处理人'),
        ),
        migrations.AddField(
            model_name='transitionapproval',
            name='weixin_notice',
            field=models.BooleanField(default=False, verbose_name='微信通知'),
        ),
        migrations.AddField(
            model_name='transitionapprovalmeta',
            name='can_edit',
            field=models.BooleanField(default=False, verbose_name='可编辑？'),
        ),
        migrations.AddField(
            model_name='transitionapprovalmeta',
            name='can_take',
            field=models.BooleanField(default=False, verbose_name='可接单？'),
        ),
        migrations.AlterField(
            model_name='state',
            name='weight',
            field=models.IntegerField(blank=True, default=99, null=True, verbose_name='权重'),
        ),
        migrations.AlterField(
            model_name='transitionapproval',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('cancelled', 'Cancelled'), ('jumped', 'Jumped')], default='pending', max_length=16, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='transitionapproval',
            name='transactioner',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='流转者'),
        ),
        migrations.AlterField(
            model_name='transitionapprovalmeta',
            name='handler_type',
            field=models.CharField(choices=[('00', '指定用户'), ('10', '指定岗位'), ('20', '指定角色'), ('30', '提交人'), ('90', '自定义审批处理类'), ('91', '自定义SQL处理人')], default='00', max_length=16, verbose_name='审批处理类型'),
        ),
        migrations.AlterField(
            model_name='transitionapprovalmeta',
            name='users',
            field=models.ManyToManyField(blank=True, db_constraint=False, related_name='_transitionapprovalmeta_users_+', to=settings.AUTH_USER_MODEL, verbose_name='指定用户'),
        ),
        migrations.AlterField(
            model_name='transitionmeta',
            name='weight',
            field=models.IntegerField(blank=True, default=99, null=True, verbose_name='权重'),
        ),
    ]
