# Generated by Django 2.2.15 on 2020-08-18 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rworkflow', '0027_auto_20200818_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conditionmeta',
            name='transition_approvale_meta',
        ),
        migrations.RemoveField(
            model_name='conditionmeta',
            name='workflow',
        ),
        migrations.DeleteModel(
            name='Condition',
        ),
        migrations.DeleteModel(
            name='ConditionMeta',
        ),
    ]
