# Generated by Django 2.2.15 on 2020-08-11 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rworkflow', '0029_auto_20200811_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transition',
            name='destination_state_value',
        ),
        migrations.RemoveField(
            model_name='transition',
            name='source_state_value',
        ),
        migrations.RemoveField(
            model_name='transitionapproval',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='transitionapproval',
            name='permissions',
        ),
    ]
