# Generated by Django 2.2.15 on 2020-08-11 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rworkflow', '0030_auto_20200811_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transitionapprovalmeta',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='transitionapprovalmeta',
            name='permissions',
        ),
    ]
