# Generated by Django 2.2.15 on 2020-08-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rworkflow', '0031_auto_20200811_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='status_field',
        ),
        migrations.RemoveField(
            model_name='state',
            name='status_value',
        ),
        migrations.AlterField(
            model_name='state',
            name='weight',
            field=models.IntegerField(blank=True, default=9, null=True, verbose_name='权重'),
        ),
    ]
