# Generated by Django 2.2.15 on 2020-08-12 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rworkflow', '0032_auto_20200811_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='transitionapproval',
            name='memo',
            field=models.TextField(default='', max_length=10000, verbose_name='批准意见'),
        ),
        migrations.AlterField(
            model_name='transitionapproval',
            name='status',
            field=models.CharField(choices=[('pending', '准备中'), ('approved', '已批准'), ('cancelled', '已取消'), ('jumped', '已跳转')], default='pending', max_length=16, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='transitionapprovalmeta',
            name='handler_type',
            field=models.CharField(choices=[('00', '指定用户'), ('10', '指定岗位'), ('20', '指定角色'), ('30', '提交人'), ('90', '自定义审批处理类'), ('91', '自定义SQL处理人')], default='30', max_length=16, verbose_name='审批处理类型'),
        ),
        migrations.AlterField(
            model_name='transitionmeta',
            name='weight',
            field=models.IntegerField(blank=True, default=9, null=True, verbose_name='权重'),
        ),
        migrations.AlterField(
            model_name='workflowinstance',
            name='initialized',
            field=models.BooleanField(default=False, editable=False, verbose_name='已初始化？'),
        ),
    ]
