# Generated by Django 2.2.15 on 2020-08-12 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rworkflow', '0033_auto_20200812_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='transitionapprovalmeta',
            name='code',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='编号'),
        ),
        migrations.AddField(
            model_name='transitionapprovalmeta',
            name='name',
            field=models.CharField(default='', max_length=128, verbose_name='名称'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transitionmeta',
            name='code',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='编号'),
        ),
        migrations.AddField(
            model_name='transitionmeta',
            name='name',
            field=models.CharField(default='', max_length=128, verbose_name='名称'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workflow',
            name='code',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='transitionapproval',
            name='transaction_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='流转时间'),
        ),
        migrations.AlterField(
            model_name='transitionapproval',
            name='workflow',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='transition_approvals', to='rworkflow.Workflow', verbose_name='工作流程'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='name',
            field=models.CharField(max_length=128, verbose_name='名称'),
        ),
    ]
