# Generated by Django 2.2.15 on 2020-08-12 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rworkflow', '0034_auto_20200812_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='transition',
            name='code',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='编号'),
        ),
        migrations.AddField(
            model_name='transition',
            name='name',
            field=models.CharField(default='', max_length=128, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='transitionapproval',
            name='code',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='编号'),
        ),
        migrations.AddField(
            model_name='transitionapproval',
            name='name',
            field=models.CharField(default='', max_length=128, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='transitionapprovalmeta',
            name='name',
            field=models.CharField(default='', max_length=128, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='transitionmeta',
            name='name',
            field=models.CharField(default='', max_length=128, verbose_name='名称'),
        ),
    ]
