# Generated by Django 2.2.15 on 2020-08-12 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rworkflow', '0035_auto_20200812_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wforder',
            name='tp',
        ),
        migrations.AddField(
            model_name='transitionapprovalmeta',
            name='can_suggestion',
            field=models.BooleanField(default=False, verbose_name='可填写处理意见？'),
        ),
        migrations.AlterField(
            model_name='state',
            name='code',
            field=models.CharField(default='', max_length=40, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='transition',
            name='code',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='transition',
            name='name',
            field=models.CharField(default='', max_length=80, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='transitionapproval',
            name='code',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='transitionapproval',
            name='memo',
            field=models.TextField(default='', max_length=10000, verbose_name='处理意见'),
        ),
        migrations.AlterField(
            model_name='transitionapproval',
            name='name',
            field=models.CharField(default='', max_length=80, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='transitionapproval',
            name='previous',
            field=models.OneToOneField(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_transition', to='rworkflow.TransitionApproval', verbose_name='前一个批准'),
        ),
        migrations.AlterField(
            model_name='transitionapproval',
            name='transaction_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='处理时间'),
        ),
        migrations.AlterField(
            model_name='transitionapproval',
            name='transactioner',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='处理者'),
        ),
        migrations.AlterField(
            model_name='transitionapproval',
            name='transition',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='transition_approvals', to='rworkflow.Transition', verbose_name='关联的流转'),
        ),
        migrations.AlterField(
            model_name='transitionapprovalmeta',
            name='code',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='transitionapprovalmeta',
            name='name',
            field=models.CharField(default='', max_length=80, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='transitionmeta',
            name='code',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='transitionmeta',
            name='name',
            field=models.CharField(default='', max_length=80, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='wforder',
            name='code',
            field=models.CharField(default='', max_length=40, verbose_name='工单编号'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='name',
            field=models.CharField(max_length=80, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='workflowcategory',
            name='code',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='workflowcategory',
            name='pinyin',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='拼音/英文'),
        ),
        migrations.AlterField(
            model_name='workflowcategory',
            name='short',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='简称'),
        ),
    ]
