# Generated by Django 2.2.15 on 2020-08-12 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rworkflow', '0038_auto_20200812_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transition',
            name='code',
            field=models.CharField(default='', max_length=40, null=True, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='transition',
            name='name',
            field=models.CharField(default='', max_length=80, null=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='transitionapproval',
            name='code',
            field=models.CharField(default='', max_length=40, null=True, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='transitionapproval',
            name='name',
            field=models.CharField(default='', max_length=80, null=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='transitionapprovalmeta',
            name='code',
            field=models.CharField(default='', max_length=40, null=True, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='transitionapprovalmeta',
            name='name',
            field=models.CharField(default='', max_length=80, null=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='transitionmeta',
            name='code',
            field=models.CharField(default='', max_length=40, null=True, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='transitionmeta',
            name='name',
            field=models.CharField(default='', max_length=80, null=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='workflowcategory',
            name='code',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='workflowcategory',
            name='pinyin',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='拼音/英文'),
        ),
        migrations.AlterField(
            model_name='workflowcategory',
            name='short',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='简称'),
        ),
    ]
