# Generated by Django 2.2.15 on 2020-08-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rworkflow', '0039_auto_20200812_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='transitionapproval',
            name='is_suggestion_required',
            field=models.BooleanField(default=False, verbose_name='处理意见是否必填？'),
        ),
        migrations.AddField(
            model_name='transitionapprovalmeta',
            name='is_suggestion_required',
            field=models.BooleanField(default=False, verbose_name='处理意见是否必填？'),
        ),
        migrations.AlterField(
            model_name='transitionapproval',
            name='status',
            field=models.CharField(choices=[('pending', '准备中'), ('approved', '已处理'), ('cancelled', '已取消'), ('jumped', '已跳转')], default='pending', max_length=16, verbose_name='状态'),
        ),
    ]
