# Generated by Django 2.2.24 on 2022-02-17 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True, verbose_name='编码')),
                ('name', models.CharField(blank=True, default='', max_length=128, verbose_name='名称')),
                ('is_locked', models.BooleanField(default=False, verbose_name='锁定')),
                ('in_use', models.BooleanField(default=False, verbose_name='使用中')),
                ('locked_at', models.DateTimeField(blank=True, null=True, verbose_name='锁定时间')),
            ],
            options={
                'verbose_name': '字典管理',
                'verbose_name_plural': '字典管理',
                'permissions': (('add_dictionary', '允许添加字典'), ('view_dictionary', '允许查看字典'), ('change_dictionary', '允许修改字典'), ('delete_dictionary', '允许删除字典'), ('import_dictionary', '允许导入字典'), ('export_dictionary', '允许导出字典')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='DictionaryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, verbose_name='编码')),
                ('label', models.CharField(blank=True, default='', max_length=128, verbose_name='标签')),
                ('master', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dictionary.Dictionary', verbose_name='字典管理')),
            ],
            options={
                'verbose_name': '字典明细',
                'verbose_name_plural': '字典明细',
                'permissions': (('add_dictionaryitem', '允许添加字典明细'), ('view_dictionaryitem', '允许查看字典明细'), ('change_dictionaryitem', '允许修改字典明细'), ('delete_dictionaryitem', '允许删除字典明细'), ('import_dictionaryitem', '允许导入字典明细'), ('export_dictionaryitem', '允许导出字典明细')),
                'default_permissions': (),
            },
        ),
    ]
