# Generated by Django 2.2.24 on 2022-02-17 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True, verbose_name='编码')),
                ('name', models.CharField(blank=True, default='', max_length=128, verbose_name='名称')),
                ('is_locked', models.BooleanField(default=False, verbose_name='锁定')),
                ('locked_at', models.DateTimeField(blank=True, null=True, verbose_name='锁定时间')),
            ],
            options={
                'verbose_name': '字典管理',
                'verbose_name_plural': '字典管理',
            },
        ),
        migrations.CreateModel(
            name='DictionarytItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=16, verbose_name='键')),
                ('value', models.CharField(blank=True, default='', max_length=128, verbose_name='值')),
                ('master', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='dictionary.Dictionary', verbose_name='字典管理')),
            ],
            options={
                'verbose_name': '字典明细',
                'verbose_name_plural': '字典明细',
            },
        ),
    ]
