# Generated by Django 2.2.24 on 2022-02-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='code',
            field=models.CharField(max_length=40, unique=True, verbose_name='编码'),
        ),
    ]
