# Generated by Django 2.2.24 on 2022-02-17 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='in_use',
            field=models.BooleanField(default=False, verbose_name='使用中'),
        ),
    ]
