# Generated by Django 2.2.24 on 2022-02-17 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_dictionary_in_use'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dictionarytitem',
            old_name='key',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='dictionarytitem',
            old_name='value',
            new_name='label',
        ),
    ]
