# Generated by Django 2.2.24 on 2022-02-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_auto_20220217_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionarytitem',
            name='code',
            field=models.CharField(max_length=16, verbose_name='编码'),
        ),
        migrations.AlterField(
            model_name='dictionarytitem',
            name='label',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='标签'),
        ),
    ]
