# Generated by Django 3.0.3 on 2020-03-02 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateField(auto_now_add=True, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_time',
            field=models.TimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
