# Generated by Django 2.2.14 on 2020-07-07 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Data do Cadastro')),
                ('payment_type', models.PositiveSmallIntegerField(blank=True, choices=[(1, '现金'), (2, '信用卡'), (3, '银行转账')], default=None, null=True, verbose_name='付款类型')),
                ('delivered', models.BooleanField(default=False)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=11)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gender', models.NullBooleanField(choices=[(0, '男'), (1, '女')], default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Product name')),
                ('value', models.DecimalField(decimal_places=2, max_digits=11)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='数量')),
                ('value', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='单价')),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11, verbose_name='总金额')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Product')),
            ],
            options={
                'verbose_name': 'Order Iten',
                'verbose_name_plural': 'Order Itens',
            },
        ),
        migrations.CreateModel(
            name='OrderProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Report Order',
                'verbose_name_plural': 'Report Orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('order.order',),
        ),
        migrations.CreateModel(
            name='ProductProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Report Order Item',
                'verbose_name_plural': 'Report Order Items',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('order.product',),
        ),
    ]
