# Generated by Django 2.2.15 on 2020-08-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrgUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='名称')),
            ],
            options={
                'verbose_name': '部门单元',
                'verbose_name_plural': '部门单元',
            },
        ),
    ]
