# Generated by Django 3.0.5 on 2020-04-26 02:33

from django.db import migrations
from django.db import connection

cursor = connection.cursor()


def forwards_func(apps, schema_editor):
    """创建视图"""
    sql = r'CREATE VIEW temp_user AS SELECT id, username, first_name FROM auth_user;'
    cursor.execute(sql)


def reverse_func(apps, schema_editor):
    """删除视图"""
    sql = r'DROP VIEW temp_user;'
    cursor.execute(sql)


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func)
    ]
