# Generated by Django 3.0.5 on 2020-04-26 02:33

from django.db import migrations
from django.contrib.auth.models import Permission, ContentType
from app01 import models


def forwards_func(apps, schema_editor):
    """创建视图"""
    cursor = schema_editor.connection.cursor()
    sql = r'CREATE VIEW temp_user AS SELECT id, username, first_name FROM auth_user;'
    cursor.execute(sql)
    content_type = ContentType.objects.get_for_model(models.TempUser)
    Permission.objects.create(
        codename='viwe_temp_user', name='Can view temp user', content_type=content_type,
    )


def reverse_func(apps, schema_editor):
    """删除视图"""
    cursor = schema_editor.connection.cursor()
    sql = r'DROP VIEW temp_user;'
    cursor.execute(sql)
    Permission.objects.filter(codename='viwe_temp_user').delete()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func)
    ]
