# Generated by Django 2.2.15 on 2020-08-13 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_auto_20200812_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='parent',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='hr.Position', verbose_name='上级岗位'),
        ),
    ]
