# Generated by Django 2.2.14 on 2020-07-28 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('user_logged_in', '用户登录成功'), ('user_logged_out', '用户登出成功'), ('user_login_failed', '用户登录失败')], max_length=64, verbose_name='动作')),
                ('action_at', models.DateTimeField(auto_now_add=True, verbose_name='动作时间')),
                ('ip', models.GenericIPAddressField(null=True, verbose_name='IP')),
                ('username', models.CharField(max_length=255, null=True, verbose_name='用户名')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '登录日志',
                'verbose_name_plural': '登录日志',
                'default_permissions': ('view',),
            },
        ),
    ]
