# Generated by Django 2.2.24 on 2021-08-18 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210818_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='删除时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, editable=False, verbose_name='已删除'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='删除时间'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, editable=False, verbose_name='已删除'),
        ),
    ]
